name: Python CI 🔎

on:
  workflow_call

jobs:
  python_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            py_modified:
              - added|modified: "./**/*.py"
      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ steps.filter.outputs.py_modified == 'true' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: ${{ steps.filter.outputs.py_modified == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Black
        if: ${{ steps.filter.outputs.py_modified == 'true' }}
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: ${{ steps.filter.outputs.py_modified_files }}
          version: "22.3.0"

      - name: Lint with flake8
        if: ${{ steps.filter.outputs.py_modified == 'true' }}
        run: |
          flake8 ${{ steps.filter.outputs.py_modified_files }}
